# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Top Tutoring
email: hello@toptutoring.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://toptutoring.com" # the base hostname & protocol for your site
client_sign_up_url: "https://app.toptutoring.com/sign_up"
tutor_sign_up_url: "https://app.toptutoring.com/users/tutors/new"
twitter_username: jekyllrb
github_username:  jekyll

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: "blog/:title"

paginate: 3
paginate_path: "blog/page:num"
excerpt_separator: ""
